# Generated by Django 4.2.2 on 2023-07-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('zone', models.CharField(blank=True, choices=[('GEC1', 'Gec1'), ('GEC2', 'Gec2'), ('Rangia', 'Rangia'), ('Bongaigaon', 'Bongaigaon'), ('Mangaldai', 'Mangaldai'), ('Kokrajhar', 'Kokrajhar'), ('Barpeta', 'Barpeta'), ('Tezpur', 'Tezpur'), ('Nagaon', 'Nagaon'), ('Morigaon', 'Morigaon'), ('Kanch', 'Kanch'), ('Cachar', 'Cachar'), ('Badarpur', 'Badarpur'), ('NLakhimpur', 'Nlakhimpur'), ('Sibsagar', 'Sibsagar'), ('Jorhat', 'Jorhat'), ('Golaghat', 'Golaghat'), ('Dibrugarh', 'Dibrugarh'), ('Tinsukia', 'Tinsukia')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.IntegerField()),
                ('issue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('division', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='connections.division')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='zone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='connections.zone'),
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.division')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.subdivision')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.zone')),
            ],
        ),
    ]
