# Generated by Django 4.2.2 on 2023-07-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_consumer_addressproof_consumer_agreementform_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='addressproof',
            new_name='Address_Proof',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='agreementform',
            new_name='Agreement_Form',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='identityproof',
            new_name='Identity_Proof',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='testreport',
            new_name='Occupency_Certificate',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='passport',
            new_name='Passport_Photo',
        ),
        migrations.AddField(
            model_name='consumer',
            name='Police_Station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='Post_Office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='Test_Report',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
