# Generated by Django 4.2.2 on 2023-07-21 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='Applied_Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.load'),
        ),
    ]
