# Generated by Django 4.2.2 on 2023-07-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_consumer_applied_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='Applied_Load',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='Village_Town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='House_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
