# Generated by Django 4.2.2 on 2023-07-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0007_consumer_applied_load_consumer_village_town_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zone',
            new_name='Circle',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='zone',
            new_name='circle',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='zone',
            new_name='circle',
        ),
    ]
