# Generated by Django 4.2.2 on 2023-07-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0008_rename_zone_circle_rename_zone_consumer_circle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'LT II DOMESTIC A'), (2, 'LT III DOMESTIC B'), (3, 'LT IV COMMERCIAL'), (4, 'LT V(A) GENERAL PURPOSE'), (5, 'LT VII AGRICULTURE'), (6, 'LT VIII SMALL INDUSTRIES (RURAL)'), (7, 'LT VIII SMALL INDUSTRIES (URBAN)'), (8, 'LT IX TEMPORARY SUPPLY (DOMESTIC)'), (9, 'LT IX TEMPORARY SUPPLY (NON DOMESTIC)'), (10, 'LT IX TEMPORARY SUPPLY (AGRICULTURE'), (11, 'LT ELECTRIC VEHICLES CHARGING'), (12, 'LT V(B) GENERAL PURPOSE (EDUCATION)')])),
            ],
        ),
    ]
