# Generated by Django 4.2.2 on 2023-07-27 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0009_loads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='Applied_Load',
            field=models.IntegerField(default=0.1, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
