# Generated by Django 4.2.2 on 2023-07-27 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0012_alter_consumer_applied_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='Applied_Load',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(25.0)]),
        ),
    ]
