# Generated by Django 4.2.2 on 2023-07-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0013_alter_consumer_applied_load'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loads',
        ),
    ]
