# Generated by Django 4.2.2 on 2023-08-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0015_remove_consumer_address_consumer_lane_consumer_road'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='Lane',
            new_name='lane',
        ),
        migrations.RenameField(
            model_name='consumer',
            old_name='Road',
            new_name='road',
        ),
        migrations.AddField(
            model_name='consumer',
            name='House_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='consumer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
